language: python
python:
  - "3.5"
  - "3.6"

# Configure where all the mails should be send
notifications:
  email:
    - florian.u.jehn@umwelt.uni-giessen.de

  # command to install dependencies
install:
  - pip install spotpy
  - python setup.py install

# command to run tests
script:
  - python acme/tests/test_genetics.py
  - python acme/tests/test_model_generators.py
  - python acme/tests/test_visualization.py
  - python acme/tests/test_examples.py
